export const GET_LOCATION_BEGINS = 'GET_LOCATION_BEGINS';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAILURE = 'GET_LOCATION_FAILURE';

export const ADD_LOCATION_BEGINS = 'ADD_LOCATION_BEGINS';
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
export const ADD_LOCATION_FAILURE = 'ADD_LOCATION_FAILURE';