version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
        - checkout
        - node/install-packages
        - run:
            command: npm run test
        - run:
            command: npm run build
workflows:
  build-deploy:
    jobs:
      - test-and-build